"""Render the agenda as HTML + plaintext and send via Amazon SES."""
from __future__ import annotations

import logging
from datetime import datetime
from html import escape
from typing import Any

import boto3

logger = logging.getLogger(__name__)

_STATUS_MARK = {"new": "•", "carried_over": "↻", "resolved": "✓", "stale": "⚠"}
_URGENCY_COLOR = {"high": "#c0392b", "medium": "#d68910", "low": "#7f8c8d"}


def render_html(agenda: dict[str, Any], week_start: datetime, week_end: datetime, mode: str = "monday") -> str:
    title = {
        "monday": "Weekly Agenda",
        "wednesday": "Mid-Week Check-in",
        "friday": "End-of-Week Recap",
    }.get(mode, "Agenda")

    def section(name: str, body: str) -> str:
        return f"<h2 style='margin-top:24px;font-size:18px'>{escape(name)}</h2>{body}"

    def ul(items: list[str]) -> str:
        if not items:
            return "<p style='color:#888'>(none)</p>"
        return "<ul style='line-height:1.55'>" + "".join(f"<li>{i}</li>" for i in items) + "</ul>"

    def status_badge(status: str) -> str:
        mark = _STATUS_MARK.get(status, "•")
        return f"<span title='{status}' style='font-weight:bold'>{mark}</span>"

    def urgency_badge(u: str) -> str:
        c = _URGENCY_COLOR.get(u, "#7f8c8d")
        return f"<span style='color:{c};font-size:11px;text-transform:uppercase'>{u}</span>"

    priorities = ul([
        f"{urgency_badge(p.get('urgency', 'medium'))} "
        f"<strong>{escape(p['title'])}</strong> — {escape(p['reason'])}"
        + (f" <em style='color:#666'>({escape(p['source_subject'])})</em>" if p.get("source_subject") else "")
        for p in agenda.get("priorities", [])
    ])
    meetings = ul([
        f"<strong>{escape(m['subject'])}</strong> "
        f"<span style='color:#888;font-size:11px'>[{escape(m.get('source', '?'))}]</span> "
        f"— {escape(m['when'])} with {escape(m['participants'])}"
        + (f"<br><span style='color:#555'>Prep: {escape(m['prep_notes'])}</span>" if m.get("prep_notes") else "")
        for m in agenda.get("meetings", [])
    ])
    actions = ul([
        f"{status_badge(a.get('status', 'new'))} "
        f"<strong>{escape(a['task'])}</strong> "
        f"<span style='color:#666;font-size:12px'>"
        f"({escape(a.get('owner', '?'))}, due {escape(a.get('due', ''))}, "
        f"{urgency_badge(a.get('urgency', 'medium'))})</span>"
        + (f" <em style='color:#666'>({escape(a['source_subject'])})</em>" if a.get("source_subject") else "")
        for a in agenda.get("action_items", [])
    ])
    follow_ups = ul([
        f"{status_badge(f.get('status', 'new'))} "
        f"<strong>{escape(f['thread'])}</strong> — waiting on "
        f"{escape(f['counterparty'])}: {escape(f['ask'])}"
        + (f" <span style='color:#888'>(open {f['weeks_open']}w)</span>" if f.get("weeks_open") else "")
        for f in agenda.get("follow_ups", [])
    ])
    promises = ul([
        f"<strong>{escape(p['commitment'])}</strong> "
        f"<span style='color:#666'>to {escape(p['to'])} by {escape(p['by'])}</span>"
        for p in agenda.get("promises_made", [])
    ])
    fyi = ul([escape(x) for x in agenda.get("fyi", [])])

    body_html = "".join([
        section("Priorities", priorities),
        section("Meetings", meetings),
        section("Action items", actions),
        section("Follow-ups (waiting on others)", follow_ups),
    ])
    if agenda.get("promises_made"):
        body_html += section("Promises you made", promises)
    body_html += section("FYI", fyi)

    return f"""\
<!doctype html>
<html><body style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;max-width:680px;margin:auto;padding:24px;color:#222">
  <h1 style="margin-bottom:4px">{escape(title)}</h1>
  <p style="color:#666;margin-top:0">{week_start.date()} – {week_end.date()}</p>
  <p style="font-size:15px;line-height:1.55">{escape(agenda.get('week_summary', ''))}</p>
  {body_html}
  <hr style="margin-top:32px;border:none;border-top:1px solid #eee">
  <p style="color:#aaa;font-size:11px">Generated by EMIS. Status: • new, ↻ carried over, ✓ resolved, ⚠ stale.</p>
</body></html>
"""


def render_text(agenda: dict[str, Any], week_start: datetime, week_end: datetime, mode: str = "monday") -> str:
    title = {
        "monday": "WEEKLY AGENDA",
        "wednesday": "MID-WEEK CHECK-IN",
        "friday": "END-OF-WEEK RECAP",
    }.get(mode, "AGENDA")

    lines = [
        title,
        f"{week_start.date()} – {week_end.date()}",
        "",
        agenda.get("week_summary", ""),
        "",
        "PRIORITIES",
    ]
    for p in agenda.get("priorities", []):
        src = f" ({p['source_subject']})" if p.get("source_subject") else ""
        lines.append(f"  • [{p.get('urgency', 'medium')}] {p['title']}{src}")
        lines.append(f"      {p['reason']}")

    lines += ["", "MEETINGS"]
    for m in agenda.get("meetings", []):
        lines.append(f"  • [{m.get('source', '?')}] {m['subject']} — {m['when']} with {m['participants']}")
        if m.get("prep_notes"):
            lines.append(f"      Prep: {m['prep_notes']}")

    lines += ["", "ACTION ITEMS"]
    for a in agenda.get("action_items", []):
        mark = _STATUS_MARK.get(a.get("status", "new"), "•")
        src = f" ({a['source_subject']})" if a.get("source_subject") else ""
        lines.append(
            f"  {mark} [{a.get('owner', '?')}, due {a.get('due', '')}, "
            f"{a.get('urgency', 'medium')}, {a.get('status', 'new')}] {a['task']}{src}"
        )

    lines += ["", "FOLLOW-UPS"]
    for f in agenda.get("follow_ups", []):
        mark = _STATUS_MARK.get(f.get("status", "new"), "•")
        weeks = f" (open {f['weeks_open']}w)" if f.get("weeks_open") else ""
        lines.append(f"  {mark} {f['thread']} — waiting on {f['counterparty']}: {f['ask']}{weeks}")

    if agenda.get("promises_made"):
        lines += ["", "PROMISES MADE"]
        for p in agenda["promises_made"]:
            lines.append(f"  • {p['commitment']} → {p['to']} by {p['by']}")

    lines += ["", "FYI"]
    for x in agenda.get("fyi", []):
        lines.append(f"  • {x}")
    return "\n".join(lines)


def send_via_ses(
    *,
    sender: str,
    recipient: str,
    subject: str,
    html: str,
    text: str,
) -> dict[str, Any]:
    client = boto3.client("ses")
    response = client.send_email(
        Source=sender,
        Destination={"ToAddresses": [recipient]},
        Message={
            "Subject": {"Data": subject, "Charset": "UTF-8"},
            "Body": {
                "Text": {"Data": text, "Charset": "UTF-8"},
                "Html": {"Data": html, "Charset": "UTF-8"},
            },
        },
    )
    logger.info("SES MessageId=%s", response["MessageId"])
    return response
